# Generated by Django 2.2.17 on 2021-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resId',
            field=models.CharField(default=[], max_length=50, verbose_name='レスポンスID'),
        ),
    ]
