# Generated by Django 2.2.17 on 2021-01-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210124_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='id',
        ),
    ]
