# Generated by Django 3.0.8 on 2021-02-03 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210124_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='')),
                ('sex', models.SmallIntegerField()),
                ('birthday', models.SmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.SmallIntegerField()),
                ('birthday', models.SmallIntegerField()),
                ('appearance', models.SmallIntegerField(default=1)),
                ('taste', models.SmallIntegerField(default=1)),
                ('condition', models.SmallIntegerField(default=1)),
                ('expire_date', models.SmallIntegerField(default=1)),
                ('expire_type', models.SmallIntegerField(default=1)),
                ('comment', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 23, 39, 11, 681340))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodClickUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
