# Generated by Django 3.0.8 on 2021-02-04 05:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_goodclickuser_response_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='res_id',
        ),
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Post', verbose_name='スレッド'),
        ),
        migrations.AlterField(
            model_name='goodclickuser',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Response', verbose_name='レスポンス'),
        ),
        migrations.AlterField(
            model_name='goodclickuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='response',
            name='appearance',
            field=models.SmallIntegerField(default=1, verbose_name='見た目'),
        ),
        migrations.AlterField(
            model_name='response',
            name='birthday',
            field=models.SmallIntegerField(verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='response',
            name='condition',
            field=models.SmallIntegerField(default=1, verbose_name='健康状態'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 14, 54, 10, 422046), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='response',
            name='expire_date',
            field=models.SmallIntegerField(default=1, verbose_name='期限切れ後N日'),
        ),
        migrations.AlterField(
            model_name='response',
            name='expire_type',
            field=models.SmallIntegerField(default=1, verbose_name='賞味or消費'),
        ),
        migrations.AlterField(
            model_name='response',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '不明'), (1, '男性'), (2, '女性')], verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='response',
            name='taste',
            field=models.SmallIntegerField(default=1, verbose_name='味'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.SmallIntegerField(verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '不明'), (1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
