# Generated by Django 3.0.8 on 2021-02-17 13:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210214_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.rename_food, verbose_name='食品イメージ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, help_text='プロフィール画像', null=True, upload_to=api.models.rename_avator, verbose_name='プロフィール画像'),
        ),
    ]
