export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const ADD_POST_SUCCESS = "ADD_POST"; 
export const FETCH_GRAPH_DATA_SUCCESS = "FETCH_GRAPH_DATA_SUCCESS";

export const ADD_RESPONSE = "ADD_RESPONSE";
export const ADD_GOOD_CLICK = "ADD_GOOD_CLICK";
export const ADD_GOOD_CLICK_SUCCESS = "ADD_GOOD_CLICK_SUCCESS";
export const ADD_SEARCH_QUERY = "ADD_SEARCH_QUERY";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR_REST = "AUTH_ERROR_REST";

export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const AUTH_CREATE_SUCCESS = "AUTH_CREATE_SUCCESS";
export const AUTH_CREATE_SUCCESS_END = "AUTH_CREATE_SUCCESS_END";
